from __future__ import annotations

from rpg.domain.models.location import HazardProfile, Location

CONTINENT_NAME = "Taklamakan"

GENERATED_LOCATIONS: dict[int, Location] = {
    1012: Location(
        id=1012,
        name="Ayazbey",
        biome="coast",
        base_level=5,
        recommended_level=6,
        x=461.00,
        y=471.00,
        factions=["ayazbeyurt_horde"],
        tags=["taklamakan", "capital", "ayazbeyurt", "culture:rohand_(human)", "religion:neverchism"],
        hazard_profile=HazardProfile(
            key="warfront",
            severity=4,
            environmental_flags=["continent:Taklamakan", "state:Ayazbeyurt", "state_full:Ayazbeyurt Horde", "group:capital", "faction:ayazbeyurt_horde", "culture_raw:Rohand (Human)", "religion_raw:Neverchism", "settlement_description:A major capital within the Ayazbeyurt Horde, a horde. Its streets are primarily populated by the Rohand (Human) culture. Population: 3179.", "hazard_severity:4"],
        ),
    ),
    1009: Location(
        id=1009,
        name="Baydi",
        biome="forest",
        base_level=5,
        recommended_level=6,
        x=762.00,
        y=273.00,
        factions=["beylik_of_bocyurt"],
        tags=["taklamakan", "capital", "bocyurt", "culture:rohand_(human)", "religion:witnesses_of_elloragh"],
        hazard_profile=HazardProfile(
            key="warfront",
            severity=4,
            environmental_flags=["continent:Taklamakan", "state:Bocyurt", "state_full:Beylik of Bocyurt", "group:capital", "faction:beylik_of_bocyurt", "culture_raw:Rohand (Human)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major capital within the Beylik of Bocyurt, a beylik. Its streets are primarily populated by the Rohand (Human) culture. Population: 3603.", "hazard_severity:4"],
        ),
    ),
    1001: Location(
        id=1001,
        name="Irewick",
        biome="forest",
        base_level=5,
        recommended_level=6,
        x=439.00,
        y=320.00,
        factions=["duchy_of_grirongria"],
        tags=["taklamakan", "capital", "grirongria", "culture:dail_(human)", "religion:neverchism"],
        hazard_profile=HazardProfile(
            key="warfront",
            severity=4,
            environmental_flags=["continent:Taklamakan", "state:Grirongria", "state_full:Duchy of Grirongria", "group:capital", "faction:duchy_of_grirongria", "culture_raw:Dail (Human)", "religion_raw:Neverchism", "settlement_description:A major capital within the Duchy of Grirongria, a duchy. Its streets are primarily populated by the Dail (Human) culture. Population: 28002.", "hazard_severity:4"],
        ),
    ),
    1005: Location(
        id=1005,
        name="Ablyntar",
        biome="desert",
        base_level=3,
        recommended_level=4,
        x=1143.00,
        y=555.00,
        factions=["kingdom_of_onimydrait"],
        tags=["taklamakan", "capital", "onimydrait", "culture:lothian_(dark_elfish)", "religion:witnesses_of_elloragh"],
        hazard_profile=HazardProfile(
            key="frontier",
            severity=2,
            environmental_flags=["continent:Taklamakan", "state:Onimydrait", "state_full:Kingdom of Onimydrait", "group:capital", "faction:kingdom_of_onimydrait", "culture_raw:Lothian (Dark Elfish)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major capital within the Kingdom of Onimydrait, a kingdom. Its streets are primarily populated by the Lothian (Dark Elfish) culture. Population: 12921.", "hazard_severity:2"],
        ),
    ),
    1002: Location(
        id=1002,
        name="Ortarith",
        biome="desert",
        base_level=5,
        recommended_level=6,
        x=1054.00,
        y=489.00,
        factions=["duchy_of_ortarith"],
        tags=["taklamakan", "capital", "ortarith", "culture:lothian_(dark_elfish)", "religion:witnesses_of_elloragh"],
        hazard_profile=HazardProfile(
            key="warfront",
            severity=4,
            environmental_flags=["continent:Taklamakan", "state:Ortarith", "state_full:Duchy of Ortarith", "group:capital", "faction:duchy_of_ortarith", "culture_raw:Lothian (Dark Elfish)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major capital within the Duchy of Ortarith, a duchy. Its streets are primarily populated by the Lothian (Dark Elfish) culture. Population: 43865.", "hazard_severity:4"],
        ),
    ),
    1008: Location(
        id=1008,
        name="Pudrock",
        biome="forest",
        base_level=5,
        recommended_level=6,
        x=293.00,
        y=262.00,
        factions=["republic_of_pudrock"],
        tags=["taklamakan", "capital", "pudrock", "culture:dail_(human)", "religion:arcanum_of_the_forefather_of_love"],
        hazard_profile=HazardProfile(
            key="warfront",
            severity=4,
            environmental_flags=["continent:Taklamakan", "state:Pudrock", "state_full:Republic of Pudrock", "group:capital", "faction:republic_of_pudrock", "culture_raw:Dail (Human)", "religion_raw:Arcanum of the Forefather of Love", "settlement_description:A major capital within the Republic of Pudrock, a republic. Its streets are primarily populated by the Dail (Human) culture. Population: 42187.", "hazard_severity:4"],
        ),
    ),
    1003: Location(
        id=1003,
        name="Yruklu",
        biome="forest",
        base_level=3,
        recommended_level=4,
        x=1137.00,
        y=364.00,
        factions=["sarprakelian_khaganate"],
        tags=["taklamakan", "capital", "sarprakeli", "culture:rohand_(human)", "religion:rohand_(human)_faith"],
        hazard_profile=HazardProfile(
            key="frontier",
            severity=2,
            environmental_flags=["continent:Taklamakan", "state:Sarprakeli", "state_full:Sarprakelian Khaganate", "group:capital", "faction:sarprakelian_khaganate", "culture_raw:Rohand (Human)", "religion_raw:Rohand (Human) Faith", "settlement_description:A major capital within the Sarprakelian Khaganate, a khaganate. Its streets are primarily populated by the Rohand (Human) culture. Population: 59273.", "hazard_severity:2"],
        ),
    ),
    1011: Location(
        id=1011,
        name="Yepeli",
        biome="tundra",
        base_level=2,
        recommended_level=3,
        x=996.00,
        y=213.00,
        factions=["republic_of_sazyurt"],
        tags=["taklamakan", "capital", "sazyurt", "culture:rohand_(human)", "religion:blasphemy_of_the_blond_spirit"],
        hazard_profile=HazardProfile(
            key="standard",
            severity=1,
            environmental_flags=["continent:Taklamakan", "state:Sazyurt", "state_full:Republic of Sazyurt", "group:capital", "faction:republic_of_sazyurt", "culture_raw:Rohand (Human)", "religion_raw:Blasphemy of the Blond Spirit", "settlement_description:A major capital within the Republic of Sazyurt, a republic. Its streets are primarily populated by the Rohand (Human) culture. Population: 13842.", "hazard_severity:1"],
        ),
    ),
    1004: Location(
        id=1004,
        name="Castme",
        biome="forest",
        base_level=2,
        recommended_level=3,
        x=402.00,
        y=234.00,
        factions=["kingdom_of_staglenia"],
        tags=["taklamakan", "capital", "staglenia", "culture:anor_(human)", "religion:neverchism"],
        hazard_profile=HazardProfile(
            key="standard",
            severity=1,
            environmental_flags=["continent:Taklamakan", "state:Staglenia", "state_full:Kingdom of Staglenia", "group:capital", "faction:kingdom_of_staglenia", "culture_raw:Anor (Human)", "religion_raw:Neverchism", "settlement_description:A major capital within the Kingdom of Staglenia, a kingdom. Its streets are primarily populated by the Anor (Human) culture. Population: 17556.", "hazard_severity:1"],
        ),
    ),
    1006: Location(
        id=1006,
        name="Shatharb",
        biome="coast",
        base_level=2,
        recommended_level=3,
        x=509.00,
        y=581.00,
        factions=["tozan_empire"],
        tags=["taklamakan", "capital", "toza", "culture:yotunn_(giants)", "religion:yotunn_(giants)ism"],
        hazard_profile=HazardProfile(
            key="standard",
            severity=1,
            environmental_flags=["continent:Taklamakan", "state:Toza", "state_full:Tozan Empire", "group:capital", "faction:tozan_empire", "culture_raw:Yotunn (Giants)", "religion_raw:Yotunn (Giants)ism", "settlement_description:A major capital within the Tozan Empire, a empire. Its streets are primarily populated by the Yotunn (Giants) culture. Population: 22018.", "hazard_severity:1"],
        ),
    ),
    1007: Location(
        id=1007,
        name="Dokuz",
        biome="tundra",
        base_level=4,
        recommended_level=5,
        x=846.00,
        y=214.00,
        factions=["vuyurt_khaganate"],
        tags=["taklamakan", "capital", "vuyurt", "culture:rohand_(human)", "religion:asunyurt_blasphemy"],
        hazard_profile=HazardProfile(
            key="contested",
            severity=3,
            environmental_flags=["continent:Taklamakan", "state:Vuyurt", "state_full:Vuyurt Khaganate", "group:capital", "faction:vuyurt_khaganate", "culture_raw:Rohand (Human)", "religion_raw:Asunyurt Blasphemy", "settlement_description:A major capital within the Vuyurt Khaganate, a khaganate. Its streets are primarily populated by the Rohand (Human) culture. Population: 13922.", "hazard_severity:3"],
        ),
    ),
    1010: Location(
        id=1010,
        name="Yar",
        biome="forest",
        base_level=5,
        recommended_level=6,
        x=579.00,
        y=332.00,
        factions=["yaryurt_horde"],
        tags=["taklamakan", "capital", "yaryurt", "culture:rohand_(human)", "religion:neverchism"],
        hazard_profile=HazardProfile(
            key="warfront",
            severity=4,
            environmental_flags=["continent:Taklamakan", "state:Yaryurt", "state_full:Yaryurt Horde", "group:capital", "faction:yaryurt_horde", "culture_raw:Rohand (Human)", "religion_raw:Neverchism", "settlement_description:A major capital within the Yaryurt Horde, a horde. Its streets are primarily populated by the Rohand (Human) culture. Population: 3187.", "hazard_severity:4"],
        ),
    ),
    1699: Location(
        id=1699,
        name="Kekeri",
        biome="coast",
        base_level=5,
        recommended_level=6,
        x=398.00,
        y=390.00,
        factions=["ayazbeyurt_horde"],
        tags=["taklamakan", "major_town", "city", "ayazbeyurt", "culture:rohand_(human)", "religion:neverchism"],
        hazard_profile=HazardProfile(
            key="warfront",
            severity=4,
            environmental_flags=["continent:Taklamakan", "state:Ayazbeyurt", "state_full:Ayazbeyurt Horde", "group:city", "faction:ayazbeyurt_horde", "culture_raw:Rohand (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Ayazbeyurt Horde. It is a stronghold of the Rohand (Human) people. Population: 16373.", "hazard_severity:4"],
        ),
    ),
    1079: Location(
        id=1079,
        name="Banocaray",
        biome="forest",
        base_level=5,
        recommended_level=6,
        x=415.00,
        y=391.00,
        factions=["ayazbeyurt_horde"],
        tags=["taklamakan", "major_town", "city", "ayazbeyurt", "culture:rohand_(human)", "religion:neverchism"],
        hazard_profile=HazardProfile(
            key="warfront",
            severity=4,
            environmental_flags=["continent:Taklamakan", "state:Ayazbeyurt", "state_full:Ayazbeyurt Horde", "group:city", "faction:ayazbeyurt_horde", "culture_raw:Rohand (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Ayazbeyurt Horde. It is a stronghold of the Rohand (Human) people. Population: 15631.", "hazard_severity:4"],
        ),
    ),
    1774: Location(
        id=1774,
        name="Ereli",
        biome="forest",
        base_level=5,
        recommended_level=6,
        x=691.00,
        y=322.00,
        factions=["beylik_of_bocyurt"],
        tags=["taklamakan", "major_town", "city", "bocyurt", "culture:rohand_(human)", "religion:neverchism"],
        hazard_profile=HazardProfile(
            key="warfront",
            severity=4,
            environmental_flags=["continent:Taklamakan", "state:Bocyurt", "state_full:Beylik of Bocyurt", "group:city", "faction:beylik_of_bocyurt", "culture_raw:Rohand (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Beylik of Bocyurt. It is a stronghold of the Rohand (Human) people. Population: 23631.", "hazard_severity:4"],
        ),
    ),
    2102: Location(
        id=2102,
        name="Erteki",
        biome="forest",
        base_level=5,
        recommended_level=6,
        x=742.00,
        y=280.00,
        factions=["beylik_of_bocyurt"],
        tags=["taklamakan", "major_town", "city", "bocyurt", "culture:rohand_(human)", "religion:neverchism"],
        hazard_profile=HazardProfile(
            key="warfront",
            severity=4,
            environmental_flags=["continent:Taklamakan", "state:Bocyurt", "state_full:Beylik of Bocyurt", "group:city", "faction:beylik_of_bocyurt", "culture_raw:Rohand (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Beylik of Bocyurt. It is a stronghold of the Rohand (Human) people. Population: 15424.", "hazard_severity:4"],
        ),
    ),
    2151: Location(
        id=2151,
        name="Eldfair",
        biome="wilderness",
        base_level=5,
        recommended_level=6,
        x=452.00,
        y=262.00,
        factions=["duchy_of_grirongria"],
        tags=["taklamakan", "major_town", "city", "grirongria", "culture:dail_(human)", "religion:neverchism"],
        hazard_profile=HazardProfile(
            key="warfront",
            severity=4,
            environmental_flags=["continent:Taklamakan", "state:Grirongria", "state_full:Duchy of Grirongria", "group:city", "faction:duchy_of_grirongria", "culture_raw:Dail (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Duchy of Grirongria. It is a stronghold of the Dail (Human) people. Population: 17606.", "hazard_severity:4"],
        ),
    ),
    2263: Location(
        id=2263,
        name="Dawngulf",
        biome="forest",
        base_level=5,
        recommended_level=6,
        x=450.00,
        y=317.00,
        factions=["duchy_of_grirongria"],
        tags=["taklamakan", "major_town", "city", "grirongria", "culture:dail_(human)", "religion:neverchism"],
        hazard_profile=HazardProfile(
            key="warfront",
            severity=4,
            environmental_flags=["continent:Taklamakan", "state:Grirongria", "state_full:Duchy of Grirongria", "group:city", "faction:duchy_of_grirongria", "culture_raw:Dail (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Duchy of Grirongria. It is a stronghold of the Dail (Human) people. Population: 16836.", "hazard_severity:4"],
        ),
    ),
    1334: Location(
        id=1334,
        name="Ertekeniz",
        biome="desert",
        base_level=5,
        recommended_level=6,
        x=1080.00,
        y=481.00,
        factions=["duchy_of_ortarith"],
        tags=["taklamakan", "major_town", "city", "ortarith", "culture:rohand_(human)", "religion:witnesses_of_elloragh"],
        hazard_profile=HazardProfile(
            key="warfront",
            severity=4,
            environmental_flags=["continent:Taklamakan", "state:Ortarith", "state_full:Duchy of Ortarith", "group:city", "faction:duchy_of_ortarith", "culture_raw:Rohand (Human)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major city within the Duchy of Ortarith. It is a stronghold of the Rohand (Human) people. Population: 26277.", "hazard_severity:4"],
        ),
    ),
    1018: Location(
        id=1018,
        name="Karond",
        biome="desert",
        base_level=5,
        recommended_level=6,
        x=1089.00,
        y=507.00,
        factions=["duchy_of_ortarith"],
        tags=["taklamakan", "major_town", "city", "ortarith", "culture:lothian_(dark_elfish)", "religion:witnesses_of_elloragh"],
        hazard_profile=HazardProfile(
            key="warfront",
            severity=4,
            environmental_flags=["continent:Taklamakan", "state:Ortarith", "state_full:Duchy of Ortarith", "group:city", "faction:duchy_of_ortarith", "culture_raw:Lothian (Dark Elfish)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major city within the Duchy of Ortarith. It is a stronghold of the Lothian (Dark Elfish) people. Population: 16002.", "hazard_severity:4"],
        ),
    ),
    1806: Location(
        id=1806,
        name="Deerchpost",
        biome="tundra",
        base_level=5,
        recommended_level=6,
        x=253.00,
        y=283.00,
        factions=["republic_of_pudrock"],
        tags=["taklamakan", "major_town", "city", "pudrock", "culture:dail_(human)", "religion:arcanum_of_the_forefather_of_love"],
        hazard_profile=HazardProfile(
            key="warfront",
            severity=4,
            environmental_flags=["continent:Taklamakan", "state:Pudrock", "state_full:Republic of Pudrock", "group:city", "faction:republic_of_pudrock", "culture_raw:Dail (Human)", "religion_raw:Arcanum of the Forefather of Love", "settlement_description:A major city within the Republic of Pudrock. It is a stronghold of the Dail (Human) people. Population: 22526.", "hazard_severity:4"],
        ),
    ),
    1829: Location(
        id=1829,
        name="Erinkor",
        biome="forest",
        base_level=3,
        recommended_level=4,
        x=1137.00,
        y=369.00,
        factions=["sarprakelian_khaganate"],
        tags=["taklamakan", "major_town", "city", "sarprakeli", "culture:rohand_(human)", "religion:rohand_(human)_faith"],
        hazard_profile=HazardProfile(
            key="frontier",
            severity=2,
            environmental_flags=["continent:Taklamakan", "state:Sarprakeli", "state_full:Sarprakelian Khaganate", "group:city", "faction:sarprakelian_khaganate", "culture_raw:Rohand (Human)", "religion_raw:Rohand (Human) Faith", "settlement_description:A major city within the Sarprakelian Khaganate. It is a stronghold of the Rohand (Human) people. Population: 27554.", "hazard_severity:2"],
        ),
    ),
    1015: Location(
        id=1015,
        name="Ayrukluyu",
        biome="forest",
        base_level=3,
        recommended_level=4,
        x=1117.00,
        y=382.00,
        factions=["sarprakelian_khaganate"],
        tags=["taklamakan", "major_town", "city", "sarprakeli", "culture:rohand_(human)", "religion:rohand_(human)_faith"],
        hazard_profile=HazardProfile(
            key="frontier",
            severity=2,
            environmental_flags=["continent:Taklamakan", "state:Sarprakeli", "state_full:Sarprakelian Khaganate", "group:city", "faction:sarprakelian_khaganate", "culture_raw:Rohand (Human)", "religion_raw:Rohand (Human) Faith", "settlement_description:A major city within the Sarprakelian Khaganate. It is a stronghold of the Rohand (Human) people. Population: 18518.", "hazard_severity:2"],
        ),
    ),
    1044: Location(
        id=1044,
        name="Kor Teli",
        biome="forest",
        base_level=3,
        recommended_level=4,
        x=1188.00,
        y=378.00,
        factions=["sarprakelian_khaganate"],
        tags=["taklamakan", "major_town", "city", "sarprakeli", "culture:rohand_(human)", "religion:rohand_(human)_faith"],
        hazard_profile=HazardProfile(
            key="frontier",
            severity=2,
            environmental_flags=["continent:Taklamakan", "state:Sarprakeli", "state_full:Sarprakelian Khaganate", "group:city", "faction:sarprakelian_khaganate", "culture_raw:Rohand (Human)", "religion_raw:Rohand (Human) Faith", "settlement_description:A major city within the Sarprakelian Khaganate. It is a stronghold of the Rohand (Human) people. Population: 17429.", "hazard_severity:2"],
        ),
    ),
    2504: Location(
        id=2504,
        name="Malant",
        biome="tundra",
        base_level=3,
        recommended_level=4,
        x=1283.00,
        y=137.00,
        factions=["sarprakelian_khaganate"],
        tags=["taklamakan", "major_town", "city", "sarprakeli", "culture:dulandir_(human)", "religion:monkhan_sect"],
        hazard_profile=HazardProfile(
            key="frontier",
            severity=2,
            environmental_flags=["continent:Taklamakan", "state:Sarprakeli", "state_full:Sarprakelian Khaganate", "group:city", "faction:sarprakelian_khaganate", "culture_raw:Dulandir (Human)", "religion_raw:Monkhan Sect", "settlement_description:A major city within the Sarprakelian Khaganate. It is a stronghold of the Dulandir (Human) people. Population: 17403.", "hazard_severity:2"],
        ),
    ),
    1135: Location(
        id=1135,
        name="Dashaat",
        biome="forest",
        base_level=3,
        recommended_level=4,
        x=1119.00,
        y=283.00,
        factions=["sarprakelian_khaganate"],
        tags=["taklamakan", "major_town", "city", "sarprakeli", "culture:dulandir_(human)", "religion:witnesses_of_elloragh"],
        hazard_profile=HazardProfile(
            key="frontier",
            severity=2,
            environmental_flags=["continent:Taklamakan", "state:Sarprakeli", "state_full:Sarprakelian Khaganate", "group:city", "faction:sarprakelian_khaganate", "culture_raw:Dulandir (Human)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major city within the Sarprakelian Khaganate. It is a stronghold of the Dulandir (Human) people. Population: 16093.", "hazard_severity:2"],
        ),
    ),
    1328: Location(
        id=1328,
        name="Arabere",
        biome="coast",
        base_level=3,
        recommended_level=4,
        x=1088.00,
        y=398.00,
        factions=["sarprakelian_khaganate"],
        tags=["taklamakan", "major_town", "city", "sarprakeli", "culture:rohand_(human)", "religion:rohand_(human)_faith"],
        hazard_profile=HazardProfile(
            key="frontier",
            severity=2,
            environmental_flags=["continent:Taklamakan", "state:Sarprakeli", "state_full:Sarprakelian Khaganate", "group:city", "faction:sarprakelian_khaganate", "culture_raw:Rohand (Human)", "religion_raw:Rohand (Human) Faith", "settlement_description:A major city within the Sarprakelian Khaganate. It is a stronghold of the Rohand (Human) people. Population: 15372.", "hazard_severity:2"],
        ),
    ),
    2091: Location(
        id=2091,
        name="Manbunel",
        biome="forest",
        base_level=3,
        recommended_level=4,
        x=1113.00,
        y=280.00,
        factions=["sarprakelian_khaganate"],
        tags=["taklamakan", "major_town", "city", "sarprakeli", "culture:dulandir_(human)", "religion:witnesses_of_elloragh"],
        hazard_profile=HazardProfile(
            key="frontier",
            severity=2,
            environmental_flags=["continent:Taklamakan", "state:Sarprakeli", "state_full:Sarprakelian Khaganate", "group:city", "faction:sarprakelian_khaganate", "culture_raw:Dulandir (Human)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major city within the Sarprakelian Khaganate. It is a stronghold of the Dulandir (Human) people. Population: 15157.", "hazard_severity:2"],
        ),
    ),
    1784: Location(
        id=1784,
        name="Crysplain",
        biome="forest",
        base_level=2,
        recommended_level=3,
        x=410.00,
        y=238.00,
        factions=["kingdom_of_staglenia"],
        tags=["taklamakan", "major_town", "city", "staglenia", "culture:anor_(human)", "religion:neverchism"],
        hazard_profile=HazardProfile(
            key="standard",
            severity=1,
            environmental_flags=["continent:Taklamakan", "state:Staglenia", "state_full:Kingdom of Staglenia", "group:city", "faction:kingdom_of_staglenia", "culture_raw:Anor (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Kingdom of Staglenia. It is a stronghold of the Anor (Human) people. Population: 20606.", "hazard_severity:1"],
        ),
    ),
    1986: Location(
        id=1986,
        name="Evillows",
        biome="wilderness",
        base_level=2,
        recommended_level=3,
        x=330.00,
        y=122.00,
        factions=["kingdom_of_staglenia"],
        tags=["taklamakan", "major_town", "city", "staglenia", "culture:anor_(human)", "religion:neverchism"],
        hazard_profile=HazardProfile(
            key="standard",
            severity=1,
            environmental_flags=["continent:Taklamakan", "state:Staglenia", "state_full:Kingdom of Staglenia", "group:city", "faction:kingdom_of_staglenia", "culture_raw:Anor (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Kingdom of Staglenia. It is a stronghold of the Anor (Human) people. Population: 15196.", "hazard_severity:1"],
        ),
    ),
    1722: Location(
        id=1722,
        name="Springmire",
        biome="tundra",
        base_level=2,
        recommended_level=3,
        x=259.00,
        y=209.00,
        factions=["kingdom_of_staglenia"],
        tags=["taklamakan", "major_town", "city", "staglenia", "culture:anor_(human)", "religion:arcanum_of_the_forefather_of_love"],
        hazard_profile=HazardProfile(
            key="standard",
            severity=1,
            environmental_flags=["continent:Taklamakan", "state:Staglenia", "state_full:Kingdom of Staglenia", "group:city", "faction:kingdom_of_staglenia", "culture_raw:Anor (Human)", "religion_raw:Arcanum of the Forefather of Love", "settlement_description:A major city within the Kingdom of Staglenia. It is a stronghold of the Anor (Human) people. Population: 15042.", "hazard_severity:1"],
        ),
    ),
    1206: Location(
        id=1206,
        name="Gostin",
        biome="desert",
        base_level=2,
        recommended_level=3,
        x=674.00,
        y=568.00,
        factions=["tozan_empire"],
        tags=["taklamakan", "major_town", "city", "toza", "culture:yotunn_(giants)", "religion:yotunn_(giants)ism"],
        hazard_profile=HazardProfile(
            key="standard",
            severity=1,
            environmental_flags=["continent:Taklamakan", "state:Toza", "state_full:Tozan Empire", "group:city", "faction:tozan_empire", "culture_raw:Yotunn (Giants)", "religion_raw:Yotunn (Giants)ism", "settlement_description:A major city within the Tozan Empire. It is a stronghold of the Yotunn (Giants) people. Population: 16843.", "hazard_severity:1"],
        ),
    ),
    1322: Location(
        id=1322,
        name="Natalfald",
        biome="wilderness",
        base_level=2,
        recommended_level=3,
        x=612.00,
        y=529.00,
        factions=["tozan_empire"],
        tags=["taklamakan", "major_town", "city", "toza", "culture:yotunn_(giants)", "religion:yotunn_(giants)ism"],
        hazard_profile=HazardProfile(
            key="standard",
            severity=1,
            environmental_flags=["continent:Taklamakan", "state:Toza", "state_full:Tozan Empire", "group:city", "faction:tozan_empire", "culture_raw:Yotunn (Giants)", "religion_raw:Yotunn (Giants)ism", "settlement_description:A major city within the Tozan Empire. It is a stronghold of the Yotunn (Giants) people. Population: 15483.", "hazard_severity:1"],
        ),
    ),
    1499: Location(
        id=1499,
        name="Buyburdi",
        biome="coast",
        base_level=4,
        recommended_level=5,
        x=1085.00,
        y=450.00,
        factions=["vuyurt_khaganate"],
        tags=["taklamakan", "major_town", "city", "vuyurt", "culture:rohand_(human)", "religion:witnesses_of_elloragh"],
        hazard_profile=HazardProfile(
            key="contested",
            severity=3,
            environmental_flags=["continent:Taklamakan", "state:Vuyurt", "state_full:Vuyurt Khaganate", "group:city", "faction:vuyurt_khaganate", "culture_raw:Rohand (Human)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major city within the Vuyurt Khaganate. It is a stronghold of the Rohand (Human) people. Population: 20115.", "hazard_severity:3"],
        ),
    ),
    1434: Location(
        id=1434,
        name="Bilta",
        biome="wilderness",
        base_level=4,
        recommended_level=5,
        x=866.00,
        y=165.00,
        factions=["vuyurt_khaganate"],
        tags=["taklamakan", "major_town", "city", "vuyurt", "culture:rohand_(human)", "religion:witnesses_of_elloragh"],
        hazard_profile=HazardProfile(
            key="contested",
            severity=3,
            environmental_flags=["continent:Taklamakan", "state:Vuyurt", "state_full:Vuyurt Khaganate", "group:city", "faction:vuyurt_khaganate", "culture_raw:Rohand (Human)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major city within the Vuyurt Khaganate. It is a stronghold of the Rohand (Human) people. Population: 18415.", "hazard_severity:3"],
        ),
    ),
    1046: Location(
        id=1046,
        name="Askibesen",
        biome="tundra",
        base_level=4,
        recommended_level=5,
        x=800.00,
        y=212.00,
        factions=["vuyurt_khaganate"],
        tags=["taklamakan", "major_town", "city", "vuyurt", "culture:rohand_(human)", "religion:witnesses_of_elloragh"],
        hazard_profile=HazardProfile(
            key="contested",
            severity=3,
            environmental_flags=["continent:Taklamakan", "state:Vuyurt", "state_full:Vuyurt Khaganate", "group:city", "faction:vuyurt_khaganate", "culture_raw:Rohand (Human)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major city within the Vuyurt Khaganate. It is a stronghold of the Rohand (Human) people. Population: 17869.", "hazard_severity:3"],
        ),
    ),
    1068: Location(
        id=1068,
        name="Ayazteke",
        biome="forest",
        base_level=4,
        recommended_level=5,
        x=889.00,
        y=239.00,
        factions=["vuyurt_khaganate"],
        tags=["taklamakan", "major_town", "city", "vuyurt", "culture:rohand_(human)", "religion:witnesses_of_elloragh"],
        hazard_profile=HazardProfile(
            key="contested",
            severity=3,
            environmental_flags=["continent:Taklamakan", "state:Vuyurt", "state_full:Vuyurt Khaganate", "group:city", "faction:vuyurt_khaganate", "culture_raw:Rohand (Human)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major city within the Vuyurt Khaganate. It is a stronghold of the Rohand (Human) people. Population: 15090.", "hazard_severity:3"],
        ),
    ),
    1563: Location(
        id=1563,
        name="Koyu",
        biome="coast",
        base_level=5,
        recommended_level=6,
        x=607.00,
        y=392.00,
        factions=["yaryurt_horde"],
        tags=["taklamakan", "major_town", "city", "yaryurt", "culture:rohand_(human)", "religion:neverchism"],
        hazard_profile=HazardProfile(
            key="warfront",
            severity=4,
            environmental_flags=["continent:Taklamakan", "state:Yaryurt", "state_full:Yaryurt Horde", "group:city", "faction:yaryurt_horde", "culture_raw:Rohand (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Yaryurt Horde. It is a stronghold of the Rohand (Human) people. Population: 15886.", "hazard_severity:4"],
        ),
    ),
    1965: Location(
        id=1965,
        name="Dozokuzka",
        biome="wilderness",
        base_level=5,
        recommended_level=6,
        x=516.00,
        y=343.00,
        factions=["yaryurt_horde"],
        tags=["taklamakan", "major_town", "city", "yaryurt", "culture:rohand_(human)", "religion:neverchism"],
        hazard_profile=HazardProfile(
            key="warfront",
            severity=4,
            environmental_flags=["continent:Taklamakan", "state:Yaryurt", "state_full:Yaryurt Horde", "group:city", "faction:yaryurt_horde", "culture_raw:Rohand (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Yaryurt Horde. It is a stronghold of the Rohand (Human) people. Population: 15684.", "hazard_severity:4"],
        ),
    ),
    2501: Location(
        id=2501,
        name="Devrek",
        biome="forest",
        base_level=5,
        recommended_level=6,
        x=509.00,
        y=329.00,
        factions=["yaryurt_horde"],
        tags=["taklamakan", "major_town", "city", "yaryurt", "culture:rohand_(human)", "religion:neverchism"],
        hazard_profile=HazardProfile(
            key="warfront",
            severity=4,
            environmental_flags=["continent:Taklamakan", "state:Yaryurt", "state_full:Yaryurt Horde", "group:city", "faction:yaryurt_horde", "culture_raw:Rohand (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Yaryurt Horde. It is a stronghold of the Rohand (Human) people. Population: 15034.", "hazard_severity:4"],
        ),
    ),
}
