-- Deprecated: schema bootstrap moved to numbered migrations.
-- Canonical source is src/rpg/infrastructure/db/migrations/000_base_schema.sql.
-- This file is intentionally retained as a no-op compatibility stub.
