-- Generated by continent_location_importer.py
-- Continent: Taklamakan
-- Locations: 40

INSERT INTO place (name)
SELECT 'Ayazbey'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Ayazbey'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1012, 461, 471, p.place_id, 'coast', 'warfront', '["continent:Taklamakan", "state:Ayazbeyurt", "state_full:Ayazbeyurt Horde", "group:capital", "faction:ayazbeyurt_horde", "culture_raw:Rohand (Human)", "religion_raw:Neverchism", "settlement_description:A major capital within the Ayazbeyurt Horde, a horde. Its streets are primarily populated by the Rohand (Human) culture. Population: 3179.", "hazard_severity:4"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Ayazbey')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Baydi'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Baydi'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1009, 762, 273, p.place_id, 'forest', 'warfront', '["continent:Taklamakan", "state:Bocyurt", "state_full:Beylik of Bocyurt", "group:capital", "faction:beylik_of_bocyurt", "culture_raw:Rohand (Human)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major capital within the Beylik of Bocyurt, a beylik. Its streets are primarily populated by the Rohand (Human) culture. Population: 3603.", "hazard_severity:4"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Baydi')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Irewick'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Irewick'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1001, 439, 320, p.place_id, 'forest', 'warfront', '["continent:Taklamakan", "state:Grirongria", "state_full:Duchy of Grirongria", "group:capital", "faction:duchy_of_grirongria", "culture_raw:Dail (Human)", "religion_raw:Neverchism", "settlement_description:A major capital within the Duchy of Grirongria, a duchy. Its streets are primarily populated by the Dail (Human) culture. Population: 28002.", "hazard_severity:4"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Irewick')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Ablyntar'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Ablyntar'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1005, 1143, 555, p.place_id, 'desert', 'frontier', '["continent:Taklamakan", "state:Onimydrait", "state_full:Kingdom of Onimydrait", "group:capital", "faction:kingdom_of_onimydrait", "culture_raw:Lothian (Dark Elfish)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major capital within the Kingdom of Onimydrait, a kingdom. Its streets are primarily populated by the Lothian (Dark Elfish) culture. Population: 12921.", "hazard_severity:2"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Ablyntar')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Ortarith'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Ortarith'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1002, 1054, 489, p.place_id, 'desert', 'warfront', '["continent:Taklamakan", "state:Ortarith", "state_full:Duchy of Ortarith", "group:capital", "faction:duchy_of_ortarith", "culture_raw:Lothian (Dark Elfish)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major capital within the Duchy of Ortarith, a duchy. Its streets are primarily populated by the Lothian (Dark Elfish) culture. Population: 43865.", "hazard_severity:4"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Ortarith')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Pudrock'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Pudrock'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1008, 293, 262, p.place_id, 'forest', 'warfront', '["continent:Taklamakan", "state:Pudrock", "state_full:Republic of Pudrock", "group:capital", "faction:republic_of_pudrock", "culture_raw:Dail (Human)", "religion_raw:Arcanum of the Forefather of Love", "settlement_description:A major capital within the Republic of Pudrock, a republic. Its streets are primarily populated by the Dail (Human) culture. Population: 42187.", "hazard_severity:4"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Pudrock')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Yruklu'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Yruklu'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1003, 1137, 364, p.place_id, 'forest', 'frontier', '["continent:Taklamakan", "state:Sarprakeli", "state_full:Sarprakelian Khaganate", "group:capital", "faction:sarprakelian_khaganate", "culture_raw:Rohand (Human)", "religion_raw:Rohand (Human) Faith", "settlement_description:A major capital within the Sarprakelian Khaganate, a khaganate. Its streets are primarily populated by the Rohand (Human) culture. Population: 59273.", "hazard_severity:2"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Yruklu')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Yepeli'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Yepeli'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1011, 996, 213, p.place_id, 'tundra', 'standard', '["continent:Taklamakan", "state:Sazyurt", "state_full:Republic of Sazyurt", "group:capital", "faction:republic_of_sazyurt", "culture_raw:Rohand (Human)", "religion_raw:Blasphemy of the Blond Spirit", "settlement_description:A major capital within the Republic of Sazyurt, a republic. Its streets are primarily populated by the Rohand (Human) culture. Population: 13842.", "hazard_severity:1"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Yepeli')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Castme'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Castme'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1004, 402, 234, p.place_id, 'forest', 'standard', '["continent:Taklamakan", "state:Staglenia", "state_full:Kingdom of Staglenia", "group:capital", "faction:kingdom_of_staglenia", "culture_raw:Anor (Human)", "religion_raw:Neverchism", "settlement_description:A major capital within the Kingdom of Staglenia, a kingdom. Its streets are primarily populated by the Anor (Human) culture. Population: 17556.", "hazard_severity:1"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Castme')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Shatharb'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Shatharb'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1006, 509, 581, p.place_id, 'coast', 'standard', '["continent:Taklamakan", "state:Toza", "state_full:Tozan Empire", "group:capital", "faction:tozan_empire", "culture_raw:Yotunn (Giants)", "religion_raw:Yotunn (Giants)ism", "settlement_description:A major capital within the Tozan Empire, a empire. Its streets are primarily populated by the Yotunn (Giants) culture. Population: 22018.", "hazard_severity:1"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Shatharb')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Dokuz'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Dokuz'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1007, 846, 214, p.place_id, 'tundra', 'contested', '["continent:Taklamakan", "state:Vuyurt", "state_full:Vuyurt Khaganate", "group:capital", "faction:vuyurt_khaganate", "culture_raw:Rohand (Human)", "religion_raw:Asunyurt Blasphemy", "settlement_description:A major capital within the Vuyurt Khaganate, a khaganate. Its streets are primarily populated by the Rohand (Human) culture. Population: 13922.", "hazard_severity:3"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Dokuz')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Yar'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Yar'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1010, 579, 332, p.place_id, 'forest', 'warfront', '["continent:Taklamakan", "state:Yaryurt", "state_full:Yaryurt Horde", "group:capital", "faction:yaryurt_horde", "culture_raw:Rohand (Human)", "religion_raw:Neverchism", "settlement_description:A major capital within the Yaryurt Horde, a horde. Its streets are primarily populated by the Rohand (Human) culture. Population: 3187.", "hazard_severity:4"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Yar')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Kekeri'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Kekeri'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1699, 398, 390, p.place_id, 'coast', 'warfront', '["continent:Taklamakan", "state:Ayazbeyurt", "state_full:Ayazbeyurt Horde", "group:city", "faction:ayazbeyurt_horde", "culture_raw:Rohand (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Ayazbeyurt Horde. It is a stronghold of the Rohand (Human) people. Population: 16373.", "hazard_severity:4"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Kekeri')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Banocaray'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Banocaray'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1079, 415, 391, p.place_id, 'forest', 'warfront', '["continent:Taklamakan", "state:Ayazbeyurt", "state_full:Ayazbeyurt Horde", "group:city", "faction:ayazbeyurt_horde", "culture_raw:Rohand (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Ayazbeyurt Horde. It is a stronghold of the Rohand (Human) people. Population: 15631.", "hazard_severity:4"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Banocaray')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Ereli'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Ereli'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1774, 691, 322, p.place_id, 'forest', 'warfront', '["continent:Taklamakan", "state:Bocyurt", "state_full:Beylik of Bocyurt", "group:city", "faction:beylik_of_bocyurt", "culture_raw:Rohand (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Beylik of Bocyurt. It is a stronghold of the Rohand (Human) people. Population: 23631.", "hazard_severity:4"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Ereli')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Erteki'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Erteki'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 2102, 742, 280, p.place_id, 'forest', 'warfront', '["continent:Taklamakan", "state:Bocyurt", "state_full:Beylik of Bocyurt", "group:city", "faction:beylik_of_bocyurt", "culture_raw:Rohand (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Beylik of Bocyurt. It is a stronghold of the Rohand (Human) people. Population: 15424.", "hazard_severity:4"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Erteki')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Eldfair'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Eldfair'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 2151, 452, 262, p.place_id, 'wilderness', 'warfront', '["continent:Taklamakan", "state:Grirongria", "state_full:Duchy of Grirongria", "group:city", "faction:duchy_of_grirongria", "culture_raw:Dail (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Duchy of Grirongria. It is a stronghold of the Dail (Human) people. Population: 17606.", "hazard_severity:4"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Eldfair')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Dawngulf'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Dawngulf'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 2263, 450, 317, p.place_id, 'forest', 'warfront', '["continent:Taklamakan", "state:Grirongria", "state_full:Duchy of Grirongria", "group:city", "faction:duchy_of_grirongria", "culture_raw:Dail (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Duchy of Grirongria. It is a stronghold of the Dail (Human) people. Population: 16836.", "hazard_severity:4"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Dawngulf')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Ertekeniz'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Ertekeniz'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1334, 1080, 481, p.place_id, 'desert', 'warfront', '["continent:Taklamakan", "state:Ortarith", "state_full:Duchy of Ortarith", "group:city", "faction:duchy_of_ortarith", "culture_raw:Rohand (Human)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major city within the Duchy of Ortarith. It is a stronghold of the Rohand (Human) people. Population: 26277.", "hazard_severity:4"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Ertekeniz')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Karond'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Karond'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1018, 1089, 507, p.place_id, 'desert', 'warfront', '["continent:Taklamakan", "state:Ortarith", "state_full:Duchy of Ortarith", "group:city", "faction:duchy_of_ortarith", "culture_raw:Lothian (Dark Elfish)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major city within the Duchy of Ortarith. It is a stronghold of the Lothian (Dark Elfish) people. Population: 16002.", "hazard_severity:4"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Karond')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Deerchpost'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Deerchpost'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1806, 253, 283, p.place_id, 'tundra', 'warfront', '["continent:Taklamakan", "state:Pudrock", "state_full:Republic of Pudrock", "group:city", "faction:republic_of_pudrock", "culture_raw:Dail (Human)", "religion_raw:Arcanum of the Forefather of Love", "settlement_description:A major city within the Republic of Pudrock. It is a stronghold of the Dail (Human) people. Population: 22526.", "hazard_severity:4"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Deerchpost')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Erinkor'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Erinkor'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1829, 1137, 369, p.place_id, 'forest', 'frontier', '["continent:Taklamakan", "state:Sarprakeli", "state_full:Sarprakelian Khaganate", "group:city", "faction:sarprakelian_khaganate", "culture_raw:Rohand (Human)", "religion_raw:Rohand (Human) Faith", "settlement_description:A major city within the Sarprakelian Khaganate. It is a stronghold of the Rohand (Human) people. Population: 27554.", "hazard_severity:2"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Erinkor')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Ayrukluyu'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Ayrukluyu'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1015, 1117, 382, p.place_id, 'forest', 'frontier', '["continent:Taklamakan", "state:Sarprakeli", "state_full:Sarprakelian Khaganate", "group:city", "faction:sarprakelian_khaganate", "culture_raw:Rohand (Human)", "religion_raw:Rohand (Human) Faith", "settlement_description:A major city within the Sarprakelian Khaganate. It is a stronghold of the Rohand (Human) people. Population: 18518.", "hazard_severity:2"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Ayrukluyu')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Kor Teli'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Kor Teli'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1044, 1188, 378, p.place_id, 'forest', 'frontier', '["continent:Taklamakan", "state:Sarprakeli", "state_full:Sarprakelian Khaganate", "group:city", "faction:sarprakelian_khaganate", "culture_raw:Rohand (Human)", "religion_raw:Rohand (Human) Faith", "settlement_description:A major city within the Sarprakelian Khaganate. It is a stronghold of the Rohand (Human) people. Population: 17429.", "hazard_severity:2"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Kor Teli')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Malant'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Malant'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 2504, 1283, 137, p.place_id, 'tundra', 'frontier', '["continent:Taklamakan", "state:Sarprakeli", "state_full:Sarprakelian Khaganate", "group:city", "faction:sarprakelian_khaganate", "culture_raw:Dulandir (Human)", "religion_raw:Monkhan Sect", "settlement_description:A major city within the Sarprakelian Khaganate. It is a stronghold of the Dulandir (Human) people. Population: 17403.", "hazard_severity:2"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Malant')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Dashaat'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Dashaat'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1135, 1119, 283, p.place_id, 'forest', 'frontier', '["continent:Taklamakan", "state:Sarprakeli", "state_full:Sarprakelian Khaganate", "group:city", "faction:sarprakelian_khaganate", "culture_raw:Dulandir (Human)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major city within the Sarprakelian Khaganate. It is a stronghold of the Dulandir (Human) people. Population: 16093.", "hazard_severity:2"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Dashaat')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Arabere'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Arabere'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1328, 1088, 398, p.place_id, 'coast', 'frontier', '["continent:Taklamakan", "state:Sarprakeli", "state_full:Sarprakelian Khaganate", "group:city", "faction:sarprakelian_khaganate", "culture_raw:Rohand (Human)", "religion_raw:Rohand (Human) Faith", "settlement_description:A major city within the Sarprakelian Khaganate. It is a stronghold of the Rohand (Human) people. Population: 15372.", "hazard_severity:2"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Arabere')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Manbunel'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Manbunel'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 2091, 1113, 280, p.place_id, 'forest', 'frontier', '["continent:Taklamakan", "state:Sarprakeli", "state_full:Sarprakelian Khaganate", "group:city", "faction:sarprakelian_khaganate", "culture_raw:Dulandir (Human)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major city within the Sarprakelian Khaganate. It is a stronghold of the Dulandir (Human) people. Population: 15157.", "hazard_severity:2"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Manbunel')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Crysplain'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Crysplain'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1784, 410, 238, p.place_id, 'forest', 'standard', '["continent:Taklamakan", "state:Staglenia", "state_full:Kingdom of Staglenia", "group:city", "faction:kingdom_of_staglenia", "culture_raw:Anor (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Kingdom of Staglenia. It is a stronghold of the Anor (Human) people. Population: 20606.", "hazard_severity:1"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Crysplain')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Evillows'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Evillows'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1986, 330, 122, p.place_id, 'wilderness', 'standard', '["continent:Taklamakan", "state:Staglenia", "state_full:Kingdom of Staglenia", "group:city", "faction:kingdom_of_staglenia", "culture_raw:Anor (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Kingdom of Staglenia. It is a stronghold of the Anor (Human) people. Population: 15196.", "hazard_severity:1"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Evillows')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Springmire'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Springmire'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1722, 259, 209, p.place_id, 'tundra', 'standard', '["continent:Taklamakan", "state:Staglenia", "state_full:Kingdom of Staglenia", "group:city", "faction:kingdom_of_staglenia", "culture_raw:Anor (Human)", "religion_raw:Arcanum of the Forefather of Love", "settlement_description:A major city within the Kingdom of Staglenia. It is a stronghold of the Anor (Human) people. Population: 15042.", "hazard_severity:1"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Springmire')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Gostin'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Gostin'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1206, 674, 568, p.place_id, 'desert', 'standard', '["continent:Taklamakan", "state:Toza", "state_full:Tozan Empire", "group:city", "faction:tozan_empire", "culture_raw:Yotunn (Giants)", "religion_raw:Yotunn (Giants)ism", "settlement_description:A major city within the Tozan Empire. It is a stronghold of the Yotunn (Giants) people. Population: 16843.", "hazard_severity:1"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Gostin')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Natalfald'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Natalfald'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1322, 612, 529, p.place_id, 'wilderness', 'standard', '["continent:Taklamakan", "state:Toza", "state_full:Tozan Empire", "group:city", "faction:tozan_empire", "culture_raw:Yotunn (Giants)", "religion_raw:Yotunn (Giants)ism", "settlement_description:A major city within the Tozan Empire. It is a stronghold of the Yotunn (Giants) people. Population: 15483.", "hazard_severity:1"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Natalfald')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Buyburdi'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Buyburdi'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1499, 1085, 450, p.place_id, 'coast', 'contested', '["continent:Taklamakan", "state:Vuyurt", "state_full:Vuyurt Khaganate", "group:city", "faction:vuyurt_khaganate", "culture_raw:Rohand (Human)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major city within the Vuyurt Khaganate. It is a stronghold of the Rohand (Human) people. Population: 20115.", "hazard_severity:3"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Buyburdi')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Bilta'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Bilta'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1434, 866, 165, p.place_id, 'wilderness', 'contested', '["continent:Taklamakan", "state:Vuyurt", "state_full:Vuyurt Khaganate", "group:city", "faction:vuyurt_khaganate", "culture_raw:Rohand (Human)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major city within the Vuyurt Khaganate. It is a stronghold of the Rohand (Human) people. Population: 18415.", "hazard_severity:3"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Bilta')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Askibesen'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Askibesen'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1046, 800, 212, p.place_id, 'tundra', 'contested', '["continent:Taklamakan", "state:Vuyurt", "state_full:Vuyurt Khaganate", "group:city", "faction:vuyurt_khaganate", "culture_raw:Rohand (Human)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major city within the Vuyurt Khaganate. It is a stronghold of the Rohand (Human) people. Population: 17869.", "hazard_severity:3"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Askibesen')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Ayazteke'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Ayazteke'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1068, 889, 239, p.place_id, 'forest', 'contested', '["continent:Taklamakan", "state:Vuyurt", "state_full:Vuyurt Khaganate", "group:city", "faction:vuyurt_khaganate", "culture_raw:Rohand (Human)", "religion_raw:Witnesses of Elloragh", "settlement_description:A major city within the Vuyurt Khaganate. It is a stronghold of the Rohand (Human) people. Population: 15090.", "hazard_severity:3"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Ayazteke')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Koyu'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Koyu'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1563, 607, 392, p.place_id, 'coast', 'warfront', '["continent:Taklamakan", "state:Yaryurt", "state_full:Yaryurt Horde", "group:city", "faction:yaryurt_horde", "culture_raw:Rohand (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Yaryurt Horde. It is a stronghold of the Rohand (Human) people. Population: 15886.", "hazard_severity:4"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Koyu')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Dozokuzka'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Dozokuzka'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 1965, 516, 343, p.place_id, 'wilderness', 'warfront', '["continent:Taklamakan", "state:Yaryurt", "state_full:Yaryurt Horde", "group:city", "faction:yaryurt_horde", "culture_raw:Rohand (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Yaryurt Horde. It is a stronghold of the Rohand (Human) people. Population: 15684.", "hazard_severity:4"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Dozokuzka')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);

INSERT INTO place (name)
SELECT 'Devrek'
WHERE NOT EXISTS (SELECT 1 FROM place WHERE LOWER(name) = LOWER('Devrek'));

INSERT INTO location (location_id, x, y, place_id, biome_key, hazard_profile_key, environmental_flags)
SELECT 2501, 509, 329, p.place_id, 'forest', 'warfront', '["continent:Taklamakan", "state:Yaryurt", "state_full:Yaryurt Horde", "group:city", "faction:yaryurt_horde", "culture_raw:Rohand (Human)", "religion_raw:Neverchism", "settlement_description:A major city within the Yaryurt Horde. It is a stronghold of the Rohand (Human) people. Population: 15034.", "hazard_severity:4"]'
FROM place p
WHERE LOWER(p.name) = LOWER('Devrek')
ON DUPLICATE KEY UPDATE
    x = VALUES(x),
    y = VALUES(y),
    place_id = VALUES(place_id),
    biome_key = VALUES(biome_key),
    hazard_profile_key = VALUES(hazard_profile_key),
    environmental_flags = VALUES(environmental_flags);
